package com.pauperinfo.card

enum class Format {
    STANDARD, FUTURE, HISTORIC, TIMELESS, GLADIATOR, PIONEER, EXPLORER,
    MODERN, LEGACY, PAUPER, VINTAGE, PENNY, COMMANDER, OATHBREAKER,
    STANDARDBRAWL, BRAWL, ALCHEMY, PAUPERCOMMANDER, DUEL, OLDSCHOOL,
    PREMODERN, PREDH
}
